import { Bytes, OnCompleteAction, type bytes } from '@algorandfoundation/algorand-typescript'
import { TestExecutionContext, toExternalValue } from '@algorandfoundation/algorand-typescript-testing'
import { beforeEach, describe, expect, test } from 'vitest'
import { PaddedTree, leafHash, siblingsFor } from '../merkle/tree'
import { Campaign } from './contract.algo'

/**
 * Behavioral tests for the Campaign escrow contract, run against the offline AVM emulation provided by
 * `algorand-typescript-testing`. The Merkle tree logic is cross-checked against the plain-TypeScript reference in
 * `../merkle/tree.ts`: after each pledge the contract's root must equal the reference `PaddedTree`, and refund/cancel
 * proofs are generated by the reference and verified by the contract.
 */

const TREE_HEIGHT = 15
const GOAL = 1_000_000 // microAlgos
const CREATION_TIME = 1_000 // patched latestTimestamp at campaign creation
const DEADLINE = 2_000 // must be strictly after CREATION_TIME
const MIN_BALANCE = 100_000
const TITLE = Bytes('My first novel')
const METADATA_URI = Bytes('ipfs://QmExample')
const MIN_DEPOSIT = 1_970_500 // µA the creator must front for fixed storage MBR

describe('Campaign', () => {
  const ctx = new TestExecutionContext()

  beforeEach(() => {
    ctx.reset()
    ctx.ledger.patchGlobalData({ latestTimestamp: CREATION_TIME })
  })

  function createCampaign(goal = GOAL, deadline = DEADLINE) {
    const contract = ctx.contract.create(Campaign)
    contract.create(TITLE, METADATA_URI, goal, deadline, depositPayment(contract))
    return contract
  }

  /**
   * The creator's storage-deposit payment to the campaign escrow.
   *
   * @param contract The campaign whose escrow to fund.
   * @returns A payment of `MIN_DEPOSIT` microAlgos from the creator.
   */
  function depositPayment(contract: Campaign) {
    const appAddress = ctx.ledger.getApplicationForContract(contract).address
    return ctx.any.txn.payment({ sender: ctx.defaultSender, receiver: appAddress, amount: MIN_DEPOSIT })
  }

  function backerAccount() {
    return ctx.any.account()
  }

  /**
   * Pledge `amount` as `backer`, mirroring the leaf in the reference tree.
   *
   * @param contract The campaign to pledge to.
   * @param tree The reference tree to mirror.
   * @param leaves The leaf hashes appended so far (mutated in place).
   * @param backer The non-creator backer.
   * @param amount Pledge amount in microAlgos.
   * @returns The slot index the pledge occupied.
   */
  function pledgeAs(contract: Campaign, tree: PaddedTree, leaves: Uint8Array[], backer: ReturnType<typeof backerAccount>, amount: number) {
    const appAddress = ctx.ledger.getApplicationForContract(contract).address
    ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: backer })]).execute(() => {
      contract.pledge(ctx.any.txn.payment({ sender: backer, receiver: appAddress, amount }))
    })
    const leaf = leafHash(toExternalValue(backer.bytes), BigInt(amount))
    leaves.push(leaf)
    return tree.append(leaf)
  }

  /**
   * Generate the `bytes[]` proof for a leaf slot from the reference tree.
   *
   * @param leaves The leaf hashes, in slot order.
   * @param index The leaf slot index.
   * @returns The `h` sibling hashes.
   */
  function proofFor(leaves: Uint8Array[], index: number): bytes[] {
    return siblingsFor(leaves, TREE_HEIGHT, index).map((sibling) => Bytes.fromBase64(Buffer.from(sibling).toString('base64')))
  }

  /**
   * The contract's root, as a Uint8Array, for comparison with the reference.
   *
   * @param contract The campaign to read.
   * @returns The root hash.
   */
  function rootOf(contract: Campaign): Uint8Array {
    return toExternalValue(contract.root.value)
  }

  describe('create', () => {
    test('sets global state and initialises the root to the empty tree', () => {
      const contract = createCampaign()

      expect(contract.creator.value).toEqual(ctx.defaultSender)
      expect(contract.title.value).toEqual(TITLE)
      expect(contract.metadataUri.value).toEqual(METADATA_URI)
      expect(contract.goal.value).toEqual(GOAL)
      expect(contract.deadline.value).toEqual(DEADLINE)
      expect(contract.raised.value).toEqual(0)
      expect(contract.status.value).toEqual(0)
      expect(contract.leafCount.value).toEqual(0)
      expect(contract.deposit.value).toEqual(MIN_DEPOSIT)
      expect(rootOf(contract)).toEqual(new PaddedTree(TREE_HEIGHT).root)
    })

    test('rejects an empty title', () => {
      const contract = ctx.contract.create(Campaign)
      expect(() => {
        contract.create(Bytes(''), METADATA_URI, GOAL, DEADLINE, depositPayment(contract))
      }).toThrow('title must not be empty')
    })

    test('rejects a goal of zero', () => {
      const contract = ctx.contract.create(Campaign)
      expect(() => {
        contract.create(TITLE, METADATA_URI, 0, DEADLINE, depositPayment(contract))
      }).toThrow('goal must be greater than zero')
    })

    test('rejects a deadline in the past', () => {
      const contract = ctx.contract.create(Campaign)
      expect(() => {
        contract.create(TITLE, METADATA_URI, GOAL, CREATION_TIME, depositPayment(contract))
      }).toThrow('deadline must be in the future')
    })

    test('rejects a deposit that is too small', () => {
      const contract = ctx.contract.create(Campaign)
      const appAddress = ctx.ledger.getApplicationForContract(contract).address
      const small = ctx.any.txn.payment({ sender: ctx.defaultSender, receiver: appAddress, amount: 100_000 })
      expect(() => {
        contract.create(TITLE, METADATA_URI, GOAL, DEADLINE, small)
      }).toThrow('deposit too small')
    })
  })

  describe('pledge', () => {
    test('appends a leaf and keeps the root in sync with the reference tree', () => {
      const contract = createCampaign()
      const tree = new PaddedTree(TREE_HEIGHT)
      const leaves: Uint8Array[] = []

      const a = backerAccount()
      const b = backerAccount()
      pledgeAs(contract, tree, leaves, a, 100_000)
      expect(rootOf(contract)).toEqual(tree.root)

      pledgeAs(contract, tree, leaves, b, 50_000)
      expect(rootOf(contract)).toEqual(tree.root)
      expect(contract.raised.value).toEqual(150_000)
      expect(contract.leafCount.value).toEqual(2)
    })

    test('rejects the creator pledging to their own campaign', () => {
      const contract = createCampaign()
      const payment = ctx.any.txn.payment({
        sender: ctx.defaultSender,
        receiver: ctx.ledger.getApplicationForContract(contract).address,
        amount: 100_000,
      })
      expect(() => {
        contract.pledge(payment)
      }).toThrow('creator cannot pledge to their own campaign')
    })

    test('rejects a zero pledge', () => {
      const contract = createCampaign()
      const payment = ctx.any.txn.payment({
        sender: ctx.defaultSender,
        receiver: ctx.ledger.getApplicationForContract(contract).address,
        amount: 0,
      })
      expect(() => {
        contract.pledge(payment)
      }).toThrow('pledge must be greater than zero')
    })

    test('rejects pledging after the deadline', () => {
      const contract = createCampaign()
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const payment = ctx.any.txn.payment({
        sender: ctx.defaultSender,
        receiver: ctx.ledger.getApplicationForContract(contract).address,
        amount: 100_000,
      })
      expect(() => {
        contract.pledge(payment)
      }).toThrow('pledging is closed')
    })
  })

  describe('refund', () => {
    test('returns a backer their pledge with a valid proof', () => {
      const contract = createCampaign()
      const tree = new PaddedTree(TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const b = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)
      pledgeAs(contract, tree, leaves, b, 40_000)

      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: 100_000 + MIN_BALANCE } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })

      const proof = proofFor(leaves, aIndex)
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        contract.refund(proof, aIndex, 60_000)
      })

      expect(contract.status.value).toEqual(1)
      const payout = ctx.txn.lastGroup.lastItxnGroup().getPaymentInnerTxn()
      expect(payout.receiver).toEqual(a)
      expect(payout.amount).toEqual(60_000)
    })

    test('rejects an invalid proof', () => {
      const contract = createCampaign()
      const tree = new PaddedTree(TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)

      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const proof = proofFor(leaves, aIndex)

      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        expect(() => {
          contract.refund(proof, aIndex, 99_999)
        }).toThrow('invalid proof')
      })
    })

    test('rejects a second refund of the same leaf', () => {
      const contract = createCampaign()
      const tree = new PaddedTree(TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)

      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: 60_000 + MIN_BALANCE } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const proof = proofFor(leaves, aIndex)

      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        contract.refund(proof, aIndex, 60_000)
        expect(() => {
          contract.refund(proof, aIndex, 60_000)
        }).toThrow('already spent')
      })
    })

    test('rejects refunding before the deadline', () => {
      const contract = createCampaign()
      expect(() => {
        contract.refund([], 0, 100_000)
      }).toThrow('deadline has not passed')
    })

    test('rejects refunding when the goal was reached', () => {
      const contract = createCampaign()
      const tree = new PaddedTree(TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      pledgeAs(contract, tree, leaves, a, GOAL)

      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        expect(() => {
          contract.refund([], 0, GOAL)
        }).toThrow('goal was reached, no refunds')
      })
    })
  })

  describe('cancelPledge', () => {
    test('returns a backer their pledge with a valid proof and decrements raised', () => {
      const contract = createCampaign()
      const tree = new PaddedTree(TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)

      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: 60_000 + MIN_BALANCE } })

      const proof = proofFor(leaves, aIndex)
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        contract.cancelPledge(proof, aIndex, 60_000)
      })

      expect(contract.raised.value).toEqual(0)
      const payout = ctx.txn.lastGroup.lastItxnGroup().getPaymentInnerTxn()
      expect(payout.amount).toEqual(60_000)
    })

    test('rejects canceling after the deadline', () => {
      const contract = createCampaign()
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      expect(() => {
        contract.cancelPledge([], 0, 100_000)
      }).toThrow('pledging is closed')
    })

    test('rejects an invalid proof', () => {
      const contract = createCampaign()
      const tree = new PaddedTree(TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)

      const proof = proofFor(leaves, aIndex)
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        expect(() => {
          contract.cancelPledge(proof, aIndex, 99_999)
        }).toThrow('invalid proof')
      })
    })
  })

  describe('claim', () => {
    test('pays the escrow balance to the creator once the goal is met', () => {
      const contract = createCampaign()
      const tree = new PaddedTree(TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const backer = backerAccount()
      const appAddress = ctx.ledger.getApplicationForContract(contract).address

      pledgeAs(contract, tree, leaves, backer, GOAL)
      ctx.ledger.patchAccountData(appAddress, { account: { balance: GOAL + MIN_BALANCE } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      contract.claim()

      expect(contract.status.value).toEqual(2)
      const payout = ctx.txn.lastGroup.lastItxnGroup().getPaymentInnerTxn()
      expect(payout.receiver).toEqual(ctx.defaultSender)
      expect(payout.amount).toEqual(GOAL)
    })

    test('rejects a second claim', () => {
      const contract = createCampaign()
      const tree = new PaddedTree(TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const backer = backerAccount()
      const appAddress = ctx.ledger.getApplicationForContract(contract).address

      pledgeAs(contract, tree, leaves, backer, GOAL)
      ctx.ledger.patchAccountData(appAddress, { account: { balance: GOAL + MIN_BALANCE } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      contract.claim()

      expect(() => {
        contract.claim()
      }).toThrow('already claimed')
    })

    test('rejects a non-creator caller', () => {
      const contract = createCampaign()
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const other = ctx.any.account()
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: other })]).execute(() => {
        expect(() => {
          contract.claim()
        }).toThrow('only the creator can claim')
      })
    })
  })

  describe('delete', () => {
    test('rejects a non-creator caller', () => {
      const contract = createCampaign()
      const other = ctx.any.account()
      ctx.txn
        .createScope([ctx.any.txn.applicationCall({ appId: contract, sender: other, onCompletion: OnCompleteAction.DeleteApplication })])
        .execute(() => {
          expect(() => {
            contract.delete()
          }).toThrow('only the creator can delete')
        })
    })

    test('rejects an open campaign', () => {
      const contract = createCampaign()
      expect(() => {
        contract.delete()
      }).toThrow('cannot delete an open campaign')
    })
  })
})
