import { Bytes, OnCompleteAction, type bytes } from '@algorandfoundation/algorand-typescript'
import { TestExecutionContext, toExternalValue } from '@algorandfoundation/algorand-typescript-testing'
import { beforeEach, describe, expect, test } from 'vitest'
import { FANOUT, WideTree, leafHash, siblingsFor } from '../merkle/tree'
import { Campaign } from './contract.algo'

/**
 * Behavioral tests for the Campaign escrow contract, run against the offline AVM emulation provided by
 * `algorand-typescript-testing`. The Merkle tree logic is cross-checked against the plain-TypeScript reference in
 * `../merkle/tree.ts`: after each pledge the contract's root must equal the reference `WideTree`, and refund/cancel
 * proofs are generated by the reference and verified by the contract.
 */

const TREE_HEIGHT = 5
const GOAL = 1_000_000 // microAlgos
const CREATION_TIME = 1_000 // patched latestTimestamp at campaign creation
const DEADLINE = 2_000 // must be strictly after CREATION_TIME
const MIN_BALANCE = 100_000
const TITLE = Bytes('My first novel')
const METADATA_URI = Bytes('ipfs://QmExample')
const DEPOSIT = 1_970_500 // µA the creator funds for fixed storage MBR

describe('Campaign', () => {
  const ctx = new TestExecutionContext()

  beforeEach(() => {
    ctx.reset()
    ctx.ledger.patchGlobalData({ latestTimestamp: CREATION_TIME })
  })

  function createCampaign(goal = GOAL, deadline = DEADLINE) {
    const contract = ctx.contract.create(Campaign)
    contract.create(TITLE, METADATA_URI, goal, deadline)
    return contract
  }

  /**
   * The creator funds the escrow's storage deposit via `fund()`.
   *
   * @param contract The campaign to fund.
   * @param amount Deposit amount in microAlgos.
   */
  function fundAs(contract: Campaign, amount = DEPOSIT) {
    const appAddress = ctx.ledger.getApplicationForContract(contract).address
    contract.fund(ctx.any.txn.payment({ sender: ctx.defaultSender, receiver: appAddress, amount }))
  }

  function backerAccount() {
    return ctx.any.account()
  }

  /**
   * Pledge `amount` as `backer`, mirroring the leaf in the reference tree.
   *
   * @param contract The campaign to pledge to.
   * @param tree The reference tree to mirror.
   * @param leaves The leaf hashes appended so far (mutated in place).
   * @param backer The non-creator backer.
   * @param amount Pledge amount in microAlgos.
   * @returns The slot index the pledge occupied.
   */
  function pledgeAs(contract: Campaign, tree: WideTree, leaves: Uint8Array[], backer: ReturnType<typeof backerAccount>, amount: number) {
    const appAddress = ctx.ledger.getApplicationForContract(contract).address
    ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: backer })]).execute(() => {
      contract.pledge(ctx.any.txn.payment({ sender: backer, receiver: appAddress, amount }))
    })
    const leaf = leafHash(toExternalValue(backer.bytes), BigInt(amount))
    leaves.push(leaf)
    return tree.append(leaf)
  }

  /**
   * Generate the Merkle proof (a single concatenated `bytes`) for a leaf slot from the reference tree.
   *
   * @param leaves The leaf hashes, in slot order.
   * @param index The leaf slot index.
   * @returns The concatenated sibling hashes, grouped by level.
   */
  function proofFor(leaves: Uint8Array[], index: number): bytes {
    const siblings = siblingsFor(leaves, FANOUT, TREE_HEIGHT, index)
    return Bytes.fromBase64(Buffer.concat(siblings).toString('base64'))
  }

  /**
   * The contract's root, as a Uint8Array, for comparison with the reference.
   *
   * @param contract The campaign to read.
   * @returns The root hash.
   */
  function rootOf(contract: Campaign): Uint8Array {
    return toExternalValue(contract.root.value)
  }

  describe('create', () => {
    test('sets global state and initialises the root to the empty tree', () => {
      const contract = createCampaign()

      expect(contract.creator.value).toEqual(ctx.defaultSender)
      expect(contract.title.value).toEqual(TITLE)
      expect(contract.metadataUri.value).toEqual(METADATA_URI)
      expect(contract.goal.value).toEqual(GOAL)
      expect(contract.deadline.value).toEqual(DEADLINE)
      expect(contract.raised.value).toEqual(0)
      expect(contract.status.value).toEqual(0)
      expect(contract.leafCount.value).toEqual(0)
      expect(contract.deposit.value).toEqual(0)
      expect(rootOf(contract)).toEqual(new WideTree(FANOUT, TREE_HEIGHT).root)
    })

    test('rejects an empty title', () => {
      const contract = ctx.contract.create(Campaign)
      expect(() => {
        contract.create(Bytes(''), METADATA_URI, GOAL, DEADLINE)
      }).toThrow('title must not be empty')
    })

    test('rejects a goal of zero', () => {
      const contract = ctx.contract.create(Campaign)
      expect(() => {
        contract.create(TITLE, METADATA_URI, 0, DEADLINE)
      }).toThrow('goal must be greater than zero')
    })

    test('rejects a deadline in the past', () => {
      const contract = ctx.contract.create(Campaign)
      expect(() => {
        contract.create(TITLE, METADATA_URI, GOAL, CREATION_TIME)
      }).toThrow('deadline must be in the future')
    })
  })

  describe('fund', () => {
    test('accumulates the creator deposit', () => {
      const contract = createCampaign()
      fundAs(contract, DEPOSIT)
      fundAs(contract, 100_000)
      expect(contract.deposit.value).toEqual(DEPOSIT + 100_000)
    })

    test('rejects a non-creator caller', () => {
      const contract = createCampaign()
      const other = ctx.any.account()
      const appAddress = ctx.ledger.getApplicationForContract(contract).address
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: other })]).execute(() => {
        expect(() => {
          contract.fund(ctx.any.txn.payment({ sender: other, receiver: appAddress, amount: DEPOSIT }))
        }).toThrow('only the creator can fund')
      })
    })

    test('rejects a zero amount', () => {
      const contract = createCampaign()
      const appAddress = ctx.ledger.getApplicationForContract(contract).address
      expect(() => {
        contract.fund(ctx.any.txn.payment({ sender: ctx.defaultSender, receiver: appAddress, amount: 0 }))
      }).toThrow('fund must be greater than zero')
    })
  })

  describe('pledge', () => {
    test('appends a leaf and keeps the root in sync with the reference tree', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []

      const a = backerAccount()
      const b = backerAccount()
      pledgeAs(contract, tree, leaves, a, 100_000)
      expect(rootOf(contract)).toEqual(tree.root)

      pledgeAs(contract, tree, leaves, b, 50_000)
      expect(rootOf(contract)).toEqual(tree.root)
      expect(contract.raised.value).toEqual(150_000)
      expect(contract.leafCount.value).toEqual(2)
    })

    test('rejects the creator pledging to their own campaign', () => {
      const contract = createCampaign()
      const payment = ctx.any.txn.payment({
        sender: ctx.defaultSender,
        receiver: ctx.ledger.getApplicationForContract(contract).address,
        amount: 100_000,
      })
      expect(() => {
        contract.pledge(payment)
      }).toThrow('creator cannot pledge to their own campaign')
    })

    test('rejects a zero pledge', () => {
      const contract = createCampaign()
      const payment = ctx.any.txn.payment({
        sender: ctx.defaultSender,
        receiver: ctx.ledger.getApplicationForContract(contract).address,
        amount: 0,
      })
      expect(() => {
        contract.pledge(payment)
      }).toThrow('pledge must be greater than zero')
    })

    test('crosses the carry point at 8 backers and keeps the root in sync', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const backers = Array.from({ length: 8 }, () => backerAccount())
      for (const backer of backers) {
        pledgeAs(contract, tree, leaves, backer, 10_000)
      }
      expect(rootOf(contract)).toEqual(tree.root)
      expect(contract.leafCount.value).toEqual(8)
    })

    test('rejects pledging after the deadline', () => {
      const contract = createCampaign()
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const payment = ctx.any.txn.payment({
        sender: ctx.defaultSender,
        receiver: ctx.ledger.getApplicationForContract(contract).address,
        amount: 100_000,
      })
      expect(() => {
        contract.pledge(payment)
      }).toThrow('pledging is closed')
    })
  })

  describe('refund', () => {
    test('returns a backer their pledge with a valid proof', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const b = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)
      pledgeAs(contract, tree, leaves, b, 40_000)

      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: 100_000 + MIN_BALANCE } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })

      const proof = proofFor(leaves, aIndex)
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        contract.refund(proof, aIndex, 60_000)
      })

      expect(contract.status.value).toEqual(1)
      const payout = ctx.txn.lastGroup.lastItxnGroup().getPaymentInnerTxn()
      expect(payout.receiver).toEqual(a)
      expect(payout.amount).toEqual(60_000)
    })

    test('rejects an invalid proof', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)

      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const proof = proofFor(leaves, aIndex)

      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        expect(() => {
          contract.refund(proof, aIndex, 99_999)
        }).toThrow('invalid proof')
      })
    })

    test('rejects a second refund of the same leaf', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)

      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: 60_000 + MIN_BALANCE } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const proof = proofFor(leaves, aIndex)

      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        contract.refund(proof, aIndex, 60_000)
        expect(() => {
          contract.refund(proof, aIndex, 60_000)
        }).toThrow('already spent')
      })
    })

    test('rejects refunding before the deadline', () => {
      const contract = createCampaign()
      expect(() => {
        contract.refund(Bytes(''), 0, 100_000)
      }).toThrow('deadline has not passed')
    })

    test('rejects refunding when the goal was reached', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      pledgeAs(contract, tree, leaves, a, GOAL)

      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        expect(() => {
          contract.refund(Bytes(''), 0, GOAL)
        }).toThrow('goal was reached, no refunds')
      })
    })
  })

  describe('cancelPledge', () => {
    test('returns a backer their pledge with a valid proof and decrements raised', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)

      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: 60_000 + MIN_BALANCE } })

      const proof = proofFor(leaves, aIndex)
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        contract.cancelPledge(proof, aIndex, 60_000)
      })

      expect(contract.raised.value).toEqual(0)
      const payout = ctx.txn.lastGroup.lastItxnGroup().getPaymentInnerTxn()
      expect(payout.amount).toEqual(60_000)
    })

    test('rejects canceling after the deadline', () => {
      const contract = createCampaign()
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      expect(() => {
        contract.cancelPledge(Bytes(''), 0, 100_000)
      }).toThrow('pledging is closed')
    })

    test('rejects an invalid proof', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)

      const proof = proofFor(leaves, aIndex)
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        expect(() => {
          contract.cancelPledge(proof, aIndex, 99_999)
        }).toThrow('invalid proof')
      })
    })

    test('re-pledge → cancel → re-pledge keeps the root in sync with the reference tree', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()

      const first = pledgeAs(contract, tree, leaves, a, 60_000)
      expect(rootOf(contract)).toEqual(tree.root)

      // Cancel the first leaf, then re-pledge a fresh leaf (the spent one stays in the tree).
      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: 60_000 + MIN_BALANCE } })
      const cancelProof = proofFor(leaves, first)
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        contract.cancelPledge(cancelProof, first, 60_000)
      })

      const second = pledgeAs(contract, tree, leaves, a, 40_000)
      expect(rootOf(contract)).toEqual(tree.root)

      // The cancelled leaf cannot be refunded (already spent), but the new leaf can.
      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: 40_000 + MIN_BALANCE } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const secondProof = proofFor(leaves, second)
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        contract.refund(secondProof, second, 40_000)
      })
    })
  })

  describe('claim', () => {
    test('pays the escrow balance to the creator once the goal is met', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const backer = backerAccount()
      const appAddress = ctx.ledger.getApplicationForContract(contract).address

      pledgeAs(contract, tree, leaves, backer, GOAL)
      ctx.ledger.patchAccountData(appAddress, { account: { balance: GOAL + MIN_BALANCE } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      contract.claim()

      expect(contract.status.value).toEqual(2)
      const payout = ctx.txn.lastGroup.lastItxnGroup().getPaymentInnerTxn()
      expect(payout.receiver).toEqual(ctx.defaultSender)
      expect(payout.amount).toEqual(GOAL)
    })

    test('rejects a second claim', () => {
      const contract = createCampaign()
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const backer = backerAccount()
      const appAddress = ctx.ledger.getApplicationForContract(contract).address

      pledgeAs(contract, tree, leaves, backer, GOAL)
      ctx.ledger.patchAccountData(appAddress, { account: { balance: GOAL + MIN_BALANCE } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      contract.claim()

      expect(() => {
        contract.claim()
      }).toThrow('already claimed')
    })

    test('rejects a non-creator caller', () => {
      const contract = createCampaign()
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const other = ctx.any.account()
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: other })]).execute(() => {
        expect(() => {
          contract.claim()
        }).toThrow('only the creator can claim')
      })
    })
  })

  describe('delete', () => {
    test('rejects a non-creator caller', () => {
      const contract = createCampaign()
      const other = ctx.any.account()
      ctx.txn
        .createScope([ctx.any.txn.applicationCall({ appId: contract, sender: other, onCompletion: OnCompleteAction.DeleteApplication })])
        .execute(() => {
          expect(() => {
            contract.delete()
          }).toThrow('only the creator can delete')
        })
    })

    test('rejects an open campaign', () => {
      const contract = createCampaign()
      expect(() => {
        contract.delete()
      }).toThrow('cannot delete an open campaign')
    })

    test('rejects when the escrow holds more than the deposit (backer funds remain)', () => {
      const contract = createCampaign()
      fundAs(contract, DEPOSIT)
      contract.status.value = 1 // failed
      const appAddress = ctx.ledger.getApplicationForContract(contract).address
      ctx.ledger.patchAccountData(appAddress, { account: { balance: DEPOSIT + 100_000 } })
      expect(() => {
        contract.delete()
      }).toThrow('cannot delete with funds remaining')
    })

    test('deletes once the escrow holds at most the deposit', () => {
      const contract = createCampaign()
      fundAs(contract, DEPOSIT)
      contract.status.value = 2 // claimed
      const appAddress = ctx.ledger.getApplicationForContract(contract).address
      ctx.ledger.patchAccountData(appAddress, { account: { balance: DEPOSIT } })
      expect(() => {
        contract.delete()
      }).not.toThrow()
    })

    test('deletes and clears the spent shards left by a refund', () => {
      const contract = createCampaign()
      fundAs(contract, DEPOSIT)
      const tree = new WideTree(FANOUT, TREE_HEIGHT)
      const leaves: Uint8Array[] = []
      const a = backerAccount()
      const aIndex = pledgeAs(contract, tree, leaves, a, 60_000)

      // Refund to create the spent shard, then delete (status Failed, only the deposit remains).
      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: 60_000 + DEPOSIT } })
      ctx.ledger.patchGlobalData({ latestTimestamp: DEADLINE })
      const proof = proofFor(leaves, aIndex)
      ctx.txn.createScope([ctx.any.txn.applicationCall({ appId: contract, sender: a })]).execute(() => {
        contract.refund(proof, aIndex, 60_000)
      })

      ctx.ledger.patchAccountData(ctx.ledger.getApplicationForContract(contract).address, { account: { balance: DEPOSIT } })
      expect(() => {
        contract.delete()
      }).not.toThrow()
    })
  })
})
