import { AlgorandClient } from '@algorandfoundation/algokit-utils'
import type { Arc56Contract } from '@algorandfoundation/algokit-utils/types/app-arc56'
import { AppFactory } from '@algorandfoundation/algokit-utils/types/app-factory'
import fs from 'node:fs'
import path from 'node:path'

/**
 * Deploys a single `Campaign` application instance.
 *
 * This is an example deployer: it loads the compiled ARC-56 spec and deploys one campaign. A real dApp would create campaigns from a
 * frontend (Phase 2), so this script is primarily an M4 milestone — proof that the compiled TEAL deploys and runs on a live network
 * (LocalNet / TestNet).
 *
 * @returns The deployed campaign's app id.
 */
export async function deploy() {
  const algorand = AlgorandClient.fromEnvironment()

  // Resolve the deployer account from the environment. On LocalNet this
  // auto-creates and funds a KMD wallet called `DEPLOYER`; on other networks it
  // reads the `DEPLOYER_MNEMONIC` env var.
  const deployer = await algorand.account.fromEnvironment('DEPLOYER')

  // Load the compiled app spec. Artifacts are generated by `npm run build` and
  // are gitignored, so this deployer must be run after a build.
  const specPath = path.resolve(__dirname, '../artifacts/campaign/Campaign.arc56.json')
  const appSpec = JSON.parse(fs.readFileSync(specPath, 'utf8')) as Arc56Contract

  const factory = new AppFactory({ appSpec, algorand, defaultSender: deployer.addr })

  const goal = 5n * 1_000_000n // 5 ALGO
  // A demo deadline 30 days in the future.
  const deadline = BigInt(Math.floor(Date.now() / 1000) + 30 * 24 * 60 * 60)

  const { result } = await factory.send.create({
    method: 'create(byte[],byte[],uint64,uint64)void',
    args: [new TextEncoder().encode('Demo campaign'), new TextEncoder().encode('ipfs://demo'), goal, deadline],
    sender: deployer.addr,
  })

  console.log(`Deployed Campaign app ${result.appId.toString()} at ${result.appAddress.toString()}`)
  return result.appId
}
