import { AlgorandClient, microAlgos } from '@algorandfoundation/algokit-utils'
import type { Arc56Contract } from '@algorandfoundation/algokit-utils/types/app-arc56'
import { AppFactory } from '@algorandfoundation/algokit-utils/types/app-factory'
import fs from 'node:fs'
import path from 'node:path'

/**
 * Deploys a single `Campaign` application instance through the full setup chain (create → fund → issue → attach → seed).
 *
 * This is an example deployer: a real dApp creates campaigns from the frontend, so this script is primarily a LocalNet sanity check that
 * the compiled TEAL deploys and runs. Requires the Factory (`FACTORY_APP_ID`) and the ClaimsVault (`VAULT_APP_ID`) to be deployed first.
 *
 * @returns The deployed campaign's app id.
 */
export async function deploy() {
  const algorand = AlgorandClient.fromEnvironment()

  // Resolve the deployer account from the environment. On LocalNet this
  // auto-creates and funds a KMD wallet called `DEPLOYER`; on other networks it
  // reads the `DEPLOYER_MNEMONIC` env var.
  const deployer = await algorand.account.fromEnvironment('DEPLOYER')

  const vaultId = process.env.VAULT_APP_ID
  if (vaultId === undefined || vaultId === '') {
    throw new Error('VAULT_APP_ID is not set — deploy the ClaimsVault first and pass its app id.')
  }

  // Load the compiled app spec. Artifacts are generated by `npm run build` and
  // are gitignored, so this deployer must be run after a build.
  const specPath = path.resolve(__dirname, '../artifacts/campaign/Campaign.arc56.json')
  const appSpec = JSON.parse(fs.readFileSync(specPath, 'utf8')) as Arc56Contract

  const factory = new AppFactory({ appSpec, algorand, defaultSender: deployer.addr })

  const goal = 5n * 1_000_000n // 5 ALGO
  // A demo deadline 30 days in the future.
  const deadline = BigInt(Math.floor(Date.now() / 1000) + 30 * 24 * 60 * 60)

  const { result } = await factory.send.create({
    method: 'create(uint64,byte[],byte[],uint64,uint64)void',
    args: [BigInt(vaultId), new TextEncoder().encode('Demo campaign'), new TextEncoder().encode('ipfs://demo'), goal, deadline],
    sender: deployer.addr,
    appReferences: [BigInt(vaultId)],
  })

  const appClient = factory.getAppClientById({ appId: result.appId })

  // Fund the storage deposit: 0.2 ALGO covers the escrow's fixed minimum balance (base + the Claim ASA opt-in).
  const payment = await algorand.createTransaction.payment({
    sender: deployer.addr,
    receiver: result.appAddress,
    amount: microAlgos(200_000n),
  })
  await appClient.send.call({
    method: 'fund(pay)void',
    args: [payment],
    sender: deployer.addr,
    extraFee: microAlgos(1000),
  })

  // The vault issues the Claim ASA; the campaign attaches it (self-opt-in); the vault seeds the supply.
  const vaultSpec = JSON.parse(
    fs.readFileSync(path.resolve(__dirname, '../artifacts/claimsvault/ClaimsVault.arc56.json'), 'utf8'),
  ) as Arc56Contract
  const vaultClient = new AppFactory({ appSpec: vaultSpec, algorand, defaultSender: deployer.addr }).getAppClientById({
    appId: BigInt(vaultId),
  })
  await vaultClient.send.call({
    method: 'issueClaimAsa(uint64)void',
    args: [result.appId],
    sender: deployer.addr,
    appReferences: [result.appId],
    extraFee: microAlgos(1000),
  })
  const claimAsa = (await vaultClient.state.box.getMapValue('asaOf', result.appId)) as bigint
  await appClient.send.call({
    method: 'attachClaimAsa(uint64)void',
    args: [claimAsa],
    sender: deployer.addr,
    appReferences: [BigInt(vaultId)],
    assetReferences: [claimAsa],
    extraFee: microAlgos(1000),
  })
  await vaultClient.send.call({
    method: 'seedSupply(uint64)void',
    args: [result.appId],
    sender: deployer.addr,
    appReferences: [result.appId],
    assetReferences: [claimAsa],
    extraFee: microAlgos(1000),
  })

  console.log(`Deployed Campaign app ${result.appId.toString()} at ${result.appAddress.toString()}`)
  return result.appId
}
