import { AlgorandClient, microAlgos } from '@algorandfoundation/algokit-utils'
import type { Arc56Contract } from '@algorandfoundation/algokit-utils/types/app-arc56'
import { AppFactory } from '@algorandfoundation/algokit-utils/types/app-factory'
import fs from 'node:fs'
import path from 'node:path'

/**
 * Deploys the platform's `ClaimsVault` application — the permanent, pooled refund escrow.
 *
 * The vault must be deployed **after** the Factory (its `create` records the Factory id, and `issueClaimAsa` reads the Factory's official
 * approval hash). The vault's application account is funded with 1 ALGO: the account base plus headroom for the parked per-campaign MBR
 * (each issued Claim ASA parks ~0.1 ALGO until garbage-collected via `destroyClaimAsa`).
 *
 * @returns The deployed vault's app id — configure it as `VITE_VAULT_APP_ID` in the frontend.
 */
export async function deploy() {
  const algorand = AlgorandClient.fromEnvironment()

  // Resolve the deployer account from the environment. On LocalNet this
  // auto-creates and funds a KMD wallet called `DEPLOYER`; on other networks it
  // reads the `DEPLOYER_MNEMONIC` env var.
  const deployer = await algorand.account.fromEnvironment('DEPLOYER')

  const factoryId = process.env.FACTORY_APP_ID
  if (factoryId === undefined || factoryId === '') {
    throw new Error('FACTORY_APP_ID is not set — deploy the Factory first and pass its app id.')
  }

  // Load the compiled app spec. Artifacts are generated by `npm run build` and
  // are gitignored, so this deployer must be run after a build.
  const specPath = path.resolve(__dirname, '../artifacts/claimsvault/ClaimsVault.arc56.json')
  const appSpec = JSON.parse(fs.readFileSync(specPath, 'utf8')) as Arc56Contract

  const factory = new AppFactory({ appSpec, algorand, defaultSender: deployer.addr })

  const { appClient } = await factory.send.create({
    method: 'create(uint64)void',
    args: [BigInt(factoryId)],
    sender: deployer.addr,
    appReferences: [BigInt(factoryId)],
  })

  // Platform storage reserve: the vault account base (0.1 ALGO) plus headroom for the parked per-campaign MBR.
  await algorand.send.payment({
    sender: deployer.addr,
    receiver: appClient.appAddress,
    amount: microAlgos(1_000_000n),
  })

  console.log(
    `Deployed ClaimsVault app ${appClient.appId.toString()} at ${appClient.appAddress.toString()}. ` +
      `Set VITE_VAULT_APP_ID=${appClient.appId.toString()} in projects/frontend/.env.`,
  )
  return appClient.appId
}
